version:          "0029--15-Feb-2024"
copyright:        "2021-2024"
title:            "Jekyll: GitHub Page Template"
author:           "J. Walker"
address:          "Box 7, Mawitaan, Bangalla."
description:
  This is a
  GitHub Page Template description. 
  See also tagline.
disclaimer:
  I have spoken.
tagline:          "This is a GitHub Page Template tagline"
keywords:         "jekyll, testing"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "Links"
  link:           "/LINKS/"
- navbar:         "Tips"
  link:           "/TIPS/"
- navbar:         "Zip File"
  link:           "/template.zip"
- navbar:         "TarBall"
  link:           "/template.tar.xz"
- navbar:         "GitHub"
  link:           "https://github.com/yforku/template/"
- navbar:         "Listing"
  link:           "/000.html"
- navbar:         "About"
  link:           "/ABOUT/"
- navbar:         "GitHub Page"
  link:           "https://template.vlsm.org/"
lang:             "en-US"
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/yforku/template/"
google_analytics: "G-KPSLWHN6H7"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

