title:       "GitHub Page Template"
version:     "0014--22-Jul-2021"
copyright:   "2021-2021"
description: >- 
  This is a
  GitHub Page Template
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-15"
author:           "J. Walker"
address:          "Box 7, Mawitaan, Bangalla."
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/template"
urlghpage:        "https://template.vlsm.org/"
keywords:         "jekyll, testing"
github:           [metadata]

